# Tarea 2 - No lineal

In [5]:
import numpy as np
from math import pi, cos, sin
##funcion del gradiente
def Gradiente1(x):
    #return np.array([3*x[0]-x[1]-2 , x[1]-x[0]])
    return np.array( [10*(-4*x[1]*x[0] + 4*x[0]**3) + 2*(1 + x[0]) , 10*(2*x[1] - 2*x[0]**2)] )  ## 1
    #return np.array([ 2*x[0]+20*pi*sin(2*pi*x[0]) , 2*x[1]+20*pi*sin(2*pi*x[1]) , 2*x[2]+20*pi*sin(2*pi*x[2]) ])  ### 2
    #return np.array([ 2*(x[0] + 2*x[1] -7) + 4*(2*x[0]+x[1]-5) , 4*(x[0]+2*x[1]-7) + 2*(2*x[0] + x[1] -5) ]) ## 3
    #return np.array([ 0.5*x[0] - 0.5*x[1] , 0.5*x[1] - 0.5*x[0] ]) ## 4
    #return np.array([ 3*x[0] - x[1] -2, x[1] - x[0] ])### prueba

def Gradiente2(x):
    #return np.array([ 2*x[0]+20*pi*sin(2*pi*x[0]) , 2*x[1]+20*pi*sin(2*pi*x[1]) , 2*x[2]+20*pi*sin(2*pi*x[2]) ])  ### 2
    return np.array([ 2*x[0]+20*pi*sin(2*pi*x[0]) , 2*x[1]+20*pi*sin(2*pi*x[1]) ])  ### 2

def Gradiente3(x):
    return np.array([ 2*(x[0] + 2*x[1] -7) + 4*(2*x[0]+x[1]-5) , 4*(x[0]+2*x[1]-7) + 2*(2*x[0] + x[1] -5) ]) ## 3
    
def Gradiente4(x):
    return np.array([ 0.5*x[0] - 0.5*x[1] , 0.5*x[1] - 0.5*x[0] ]) ## 4


def Hessiana1(x):
    #return np.array([ [3,-1] , [-1,1] ])### experimento
    return np.array([ [-40*x[1] + 120*x[0]**2 +2, -40*x[0] ],[-40*x[0], 20] ]) # 1
    #return np.array([[2 + 40*pi**2*cos(2*pi*x[0]), 0, 0],[0 ,2 + 40*pi**2*cos(2*pi*x[1]), 0],[0, 0, 2 + 40*pi**2*cos(2*pi*x[2])]])
    #return np.array([ [10,8] , [8,10] ])#3
    #return np.array([ [0.5,-0.5] , [-0.5,0.5] ])#4

    
def Hessiana2(x):
    #return np.array([[2 + 40*pi**2*cos(2*pi*x[0]), 0, 0],[0 ,2 + 40*pi**2*cos(2*pi*x[1]), 0],[0, 0, 2 + 40*pi**2*cos(2*pi*x[2])]])
    return np.array([[2 + 40*pi**2*cos(2*pi*x[0]), 0],[0 ,2 + 40*pi**2*cos(2*pi*x[1])]  ])
 
def Hessiana3(x):
    return np.array([ [10,8] , [8,10] ])#3

def Hessiana4(x):
    return np.array([ [0.5,-0.5] , [-0.5,0.5] ])#4
    
class Solvers():
    def __init__(self, obj_function, gradient, hessiana, solver='gd',
             alpha = 0.01, tol = 1e-3,max_iter=10):
        self.obj_function = obj_function
        self.gradient = gradient
        ##
        self.hessiana = hessiana
        ##
        self.alpha = alpha
        self.tol = tol
        self.max_iter = max_iter
        ## le hizo falta agregar esto al profesor
        self.solver=solver
        ##
        
    def __gd_solver(self, start_point):
        grad_ = self.gradient(start_point)
        convergence = np.dot(grad_,grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        while not stop:
            ###### 
            print("El {} valor es: {}".format(iter_,point))
            iter_+=1 #Tambien le hizo falta esta parte al profesor
            ###### 
            point = point - self.alpha*grad_
            grad_ = self.gradient(point)
            stop = ((np.dot(grad_,grad_)) < self.tol) or\
                (iter_ > self.max_iter)
        return point
    
    #### metodo de newton
    def __mn_solver(self, start_point):
        grad_ = self.gradient(start_point)
        convergence = np.dot(grad_,grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        hess_ = self.hessiana(start_point)
        while not stop:
            ###### 
            print("El {} valor es: {}".format(iter_,point))
            iter_+=1 #Tambien le hizo falta esta parte al profesor
            ###### 
            hess1 = np.linalg.inv(hess_)
            point = point - np.dot(hess1,grad_)
            grad_ = self.gradient(point)
            hess_ = self.hessiana(point)
            stop = ((np.dot(grad_,grad_)) < self.tol) or\
                (iter_ > self.max_iter)
        print("El {} valor es: {}".format(iter_,point))
        return point
            
    def solve(self, start_point):
        if self.solver=='gd':
            return self.__gd_solver(start_point)
        elif self.solver=='mn':
            return self.__mn_solver(start_point)
        else:
            raise ValueError('Undefined solver')

Primer ejercicio de la tarea Gradiente Descendiente

In [6]:
## ejercicio 1
x=[0,0]
f = 10*(x[1] - x[0]**2)**2 + (1 - x[0])**2
p_1=Solvers(f,Gradiente1,Hessiana1,solver='gd')
p_1.solve(x)

El 0 valor es: [0, 0]
El 1 valor es: [-0.02  0.  ]
El 2 valor es: [-3.95968e-02  8.00000e-05]
El 3 valor es: [-0.0587813   0.00037758]
El 4 valor es: [-0.07753331  0.00099311]
El 5 valor es: [-0.09582701  0.00199677]
El 6 valor es: [-0.11363502  0.00343398]
El 7 valor es: [-0.13093146  0.00532977]
El 8 valor es: [-0.14769414  0.00769242]
El 9 valor es: [-0.16390602  0.01051665]
El 10 valor es: [-0.17955605  0.01378636]


array([-0.19463951,  0.01747716])

In [16]:
# ejercicio 3 
x=[0,0]
f = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2
p_1=Solvers(f,Gradiente3,Hessiana3,solver='gd')
p_1.solve(x)

El 0 valor es: [0, 0]
El 1 valor es: [0.34 0.38]
El 2 valor es: [0.6156 0.6948]
El 3 valor es: [0.838456 0.956072]
El 4 valor es: [1.01812464 1.17338832]
El 5 valor es: [1.16244111 1.35459952]
El 6 valor es: [1.27782904 1.50614428]
El 7 valor es: [1.36955459 1.63330353]
El 8 valor es: [1.44193485 1.74040881]
El 9 valor es: [1.49850866 1.83101314]
El 10 valor es: [1.54217674 1.90803113]


array([1.57531658, 1.97385388])

In [5]:
# ejercicio 4
x=[0,0]
f = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1])
p_1=Solvers(f,Gradiente4,Hessiana4,solver='gd')
p_1.solve(x)

[0, 0]

In [6]:
# ejercicio 2
x=[0,0]
f = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) 
p_1=Solvers(f,Gradiente2,Hessiana2,solver='gd')
p_1.solve(x)

[0, 0]

## Método de newton

In [17]:
## ejercicio 1 
x=[0,0]
f = 10*(x[1] - x[0]**2)**2 + (1 - x[0])**2
p_1=Solvers(f,Gradiente1,Hessiana1,solver='mn')
p_1.solve(x)

El 0 valor es: [0, 0]
El 1 valor es: [-1.  0.]
El 2 valor es: [-1.  1.]


array([-1.,  1.])

In [18]:
# Ejercicio 2 - metodo de newton
x=[0,0]
f = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1]))
p_1=Solvers(f,Gradiente2,Hessiana2,solver='mn')
p_1.solve(x)

El 0 valor es: [0, 0]


[0, 0]

In [19]:
# Ejercicio 3 - metodo de newton
x=[0,0]
f = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2
p_1=Solvers(f,Gradiente3,Hessiana3,solver='mn')
p_1.solve(x)

El 0 valor es: [0, 0]
El 1 valor es: [1. 3.]


array([1., 3.])

In [20]:
# Ejercicio 4 - metodo de newton
x=[0,0]
f = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1])
p_1=Solvers(f,Gradiente4,Hessiana4,solver='mn')
p_1.solve(x)

El 0 valor es: [0, 0]


[0, 0]

## Gradiente descendente con diferencias finitas

In [7]:
import numpy as np
from math import pi, cos, sin
def Gradiente1(x):
    h = 0.05
    xa = [x[0]+h,x[1]]
    #x = [x[0]+h,x[1],x[2]]## 2
    m1 = 10*(xa[1] - xa[0]**2)**2 + (1 - xa[0])**2##1
    #m1 = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))## 2
    #m1 = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2 ## 3
    #m1 = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1]) ## 4
    
    xa = [x[0]-h,x[1]]
    #x = [x[0]-h,x[1],x[2]]##2
    m2 = 10*(xa[1] - xa[0]**2)**2 + (1 - xa[0])**2##1
    #m2 = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))##2
    #m2 = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2 ## 3
    #m2 = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1])##4
    f1 = (m1-m2)/(2*h)
    
    xa = [x[0],x[1]+h]
    #x = [x[0],x[1]+h,x[2]]##2
    p1 = 10*(xa[1] - xa[0]**2)**2 + (1 - xa[0])**2##1
    #p1 = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))##2
    #p1 = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2 ## 3
    #p1 = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1])## 4
    
    xa = [x[0],x[1]-h]
    #x = [x[0],x[1]-h,x[2]]##2
    p2 = 10*(xa[1] - xa[0]**2)**2 + (1 - xa[0])**2##1
    #p2 = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))##2
    #p2 = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2 ## 3
    #p2 = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1]) ## 4
    f2 = (p1-p2)/(2*h)
    
    #x = [x[0],x[1],x[2]+h]##2
    #s1 = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))##2
    #x = [x[0],x[1],x[2]-h]##2
    #s2 = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))##2
    #f3 = (s1-s2)/(2*h)##2
    
    return np.array([f1,f2])
    #return np.array([f1,f2,f2]) ## 2

def Gradiente2(x):
    h = 0.05
    xa = [x[0]+h,x[1],x[2]]## 2
    m1 = 30 + (xa[0]**2 - 10*cos(2*pi*xa[0])) + (xa[1]**2 - 10*cos(2*pi*xa[1])) + (xa[2]**2 - 10*cos(2*pi*xa[2]))## 2
    xa = [x[0]-h,x[1],x[2]]##2
    m2 = 30 + (xa[0]**2 - 10*cos(2*pi*xa[0])) + (xa[1]**2 - 10*cos(2*pi*xa[1])) + (xa[2]**2 - 10*cos(2*pi*xa[2]))##2
    f1 = (m1-m2)/(2*h)
    
    xa = [x[0],x[1]+h,x[2]]##2
    p1 = 30 + (xa[0]**2 - 10*cos(2*pi*xa[0])) + (xa[1]**2 - 10*cos(2*pi*xa[1])) + (xa[2]**2 - 10*cos(2*pi*xa[2]))##2
    xa = [x[0],x[1]-h,x[2]]##2
    p2 = 30 + (xa[0]**2 - 10*cos(2*pi*xa[0])) + (xa[1]**2 - 10*cos(2*pi*xa[1])) + (xa[2]**2 - 10*cos(2*pi*xa[2]))##2
    f2 = (p1-p2)/(2*h)
    
    xa = [x[0],x[1],x[2]+h]##2
    s1 = 30 + (xa[0]**2 - 10*cos(2*pi*xa[0])) + (xa[1]**2 - 10*cos(2*pi*xa[1])) + (xa[2]**2 - 10*cos(2*pi*xa[2]))##2
    xa = [x[0],x[1],x[2]-h]##2
    s2 = 30 + (xa[0]**2 - 10*cos(2*pi*xa[0])) + (xa[1]**2 - 10*cos(2*pi*xa[1])) + (xa[2]**2 - 10*cos(2*pi*xa[2]))##2
    f3 = (s1-s2)/(2*h)##2
    return np.array([f1,f2,f2]) ## 2    
    
    
def Gradiente4(x):
    h = 0.05
    xa = [x[0]+h,x[1]]
    m1 = 0.25*(xa[0]**2 + xa[1]**2) - 0.5*(xa[0]*xa[1]) ## 4
    
    xa = [x[0]-h,x[1]]
    m2 = 0.25*(xa[0]**2 + xa[1]**2) - 0.5*(xa[0]*xa[1])##4
    f1 = (m1-m2)/(2*h)
    
    xa = [x[0],x[1]+h]
    p1 = 0.25*(xa[0]**2 + xa[1]**2) - 0.5*(xa[0]*xa[1])## 4
    
    xa = [x[0],x[1]-h]
    p2 = 0.25*(xa[0]**2 + xa[1]**2) - 0.5*(xa[0]*xa[1]) ## 4
    f2 = (p1-p2)/(2*h)
    return np.array([f1,f2])

def Gradiente3(x):
    h = 0.05
    xa = [x[0]+h,x[1]]
    m1 = (xa[0] + 2*xa[1] -7)**2 + (2*xa[0] + xa[1] - 5)**2 ## 3  
    xa = [x[0]-h,x[1]]
    m2 = (xa[0] + 2*xa[1] -7)**2 + (2*xa[0] + xa[1] - 5)**2 ## 3
    f1 = (m1-m2)/(2*h)
    xa = [x[0],x[1]+h]
    p1 = (xa[0] + 2*xa[1] -7)**2 + (2*xa[0] + xa[1] - 5)**2 ## 3
    xa = [x[0],x[1]-h]
    p2 = (xa[0] + 2*xa[1] -7)**2 + (2*xa[0] + xa[1] - 5)**2 ## 3
    f2 = (p1-p2)/(2*h)
    return np.array([f1,f2])  
    
def Hessiana2(x):
    return np.array([[2 + 40*pi**2*cos(2*pi*x[0]), 0, 0],[0 ,2 + 40*pi**2*cos(2*pi*x[1]), 0],[0, 0, 2 + 40*pi**2*cos(2*pi*x[2])]])

def Hessiana1(x):
    #return np.array([ [3,-1] , [-1,1] ])### experimento
    return np.array([ [-40*x[1] + 120*x[0]**2 +2, -40*x[0] ],[-40*x[0], 20] ]) # 1
    #return np.array([[2 + 40*pi**2*cos(2*pi*x[0]), 0, 0],[0 ,2 + 40*pi**2*cos(2*pi*x[1]), 0],[0, 0, 2 + 40*pi**2*cos(2*pi*x[2])]])
    #return np.array([ [10,8] , [8,10] ])#3
    #return np.array([ [0.5,-0.5] , [-0.5,0.5] ])#4
    
def Hessiana3(x):
    return np.array([ [10,8] , [8,10] ])#3

def Hessiana4(x):
    return np.array([ [0.5,-0.5] , [-0.5,0.5] ])#4
    
    
class Solvers():
    def __init__(self, obj_function, gradient, hessiana, solver='gd',
             alpha = 0.01, tol = 1e-3,max_iter=10):
        self.obj_function = obj_function
        self.gradient = gradient
        ##
        self.hessiana = hessiana
        ##
        self.alpha = alpha
        self.tol = tol
        self.max_iter = max_iter
        ## le hizo falta agregar esto al profesor
        self.solver=solver
        ##
        
    def __gd_solver(self, start_point):
        grad_ = self.gradient(start_point)
        convergence = np.dot(grad_,grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        while not stop:
            ###### 
            print("El {} valor, es: {}".format(iter_,point))
            iter_+=1 #Tambien le hizo falta esta parte al profesor
            ###### 
            point = point - self.alpha*grad_
            grad_ = self.gradient(point)
            stop = ((np.dot(grad_,grad_)) < self.tol) or\
                (iter_ > self.max_iter)
        return point
    
    #### metodo de newton
    def __mn_solver(self, start_point):
        grad_ = self.gradient(start_point)
        convergence = np.dot(grad_,grad_)
        stop = (convergence < self.tol)
        iter_ = 0
        point = start_point
        hess_ = self.hessiana(start_point)
        while not stop:
            ###### 
            #print("El {} valor es: {}".format(iter_,point))
            iter_+=1 #Tambien le hizo falta esta parte al profesor
            ###### 
            hess1 = np.linalg.inv(hess_)
            point = point - np.dot(hess1,grad_)
            grad_ = self.gradient(point)
            hess_ = self.hessiana(start_point)
            stop = ((np.dot(grad_,grad_)) < self.tol) or\
                (iter_ > self.max_iter)
        print("El {} valor es: {}".format(iter_,point))
        return point
            
    def solve(self, start_point):
        if self.solver=='gd':
            return self.__gd_solver(start_point)
        elif self.solver=='mn':
            return self.__mn_solver(start_point)
        else:
            raise ValueError('Undefined solver')

In [2]:
## ejercicio 1 
x=[0,0]
f = 10*(x[1] - x[0]**2)**2 + (1 - x[0])**2
p_1=Solvers(f,Gradiente1,Hessiana1,solver='gd')
p_1.solve(x)

El 0 valor, es: [0, 0]
El 1 valor, es: [0.02 0.  ]
El 2 valor, es: [3.95768e-02 8.00000e-05]
El 3 valor, es: [0.05872216 0.00037726]
El 4 valor, es: [0.07741686 0.00099147]
El 5 valor, es: [0.09563621 0.00199185]
El 6 valor, es: [0.11335416 0.00342274]
El 7 valor, es: [0.13054631 0.00530802]
El 8 valor, es: [0.14719209 0.00765489]
El 9 valor, es: [0.16327616 0.01045701]
El 10 valor, es: [0.17878919 0.01369743]


array([0.19372816, 0.01735106])

In [8]:
# ejercicio 2
x=[0,0,0]
f = 30 + (x[0]**2 - 10*cos(2*pi*x[0])) + (x[1]**2 - 10*cos(2*pi*x[1])) + (x[2]**2 - 10*cos(2*pi*x[2]))
p_1=Solvers(f,Gradiente2,Hessiana2,solver='gd')
p_1.solve(x)

[0, 0, 0]

In [9]:
# ejercicio 3
x=[0,0]
f = (x[0] + 2*x[1] -7)**2 + (2*x[0] + x[1] - 5)**2
p_1=Solvers(f,Gradiente3,Hessiana3,solver='gd')
p_1.solve(x)

El 0 valor, es: [0, 0]
El 1 valor, es: [0.34 0.38]
El 2 valor, es: [0.6156 0.6948]
El 3 valor, es: [0.838456 0.956072]
El 4 valor, es: [1.01812464 1.17338832]
El 5 valor, es: [1.16244111 1.35459952]
El 6 valor, es: [1.27782904 1.50614428]
El 7 valor, es: [1.36955459 1.63330353]
El 8 valor, es: [1.44193485 1.74040881]
El 9 valor, es: [1.49850866 1.83101314]
El 10 valor, es: [1.54217674 1.90803113]


array([1.57531658, 1.97385388])

In [10]:
# ejercicio 4
x=[0,0]
f = 0.25*(x[0]**2 + x[1]**2) - 0.5*(x[0]*x[1])
p_1=Solvers(f,Gradiente4,Hessiana4,solver='gd')
p_1.solve(x)

[0, 0]